name: broke_club
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.8
  
  # Navigation
  go_router: ^15.1.1
  
  # State Management
  provider: ^6.1.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  
  # Data Persistence
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Network
  http: ^1.2.2
  dio: ^5.4.0
  
  # Utilities
  uuid: ^4.2.1
  intl: ^0.19.0
  crypto: ^3.0.3
  
  # Charts & Visualization
  fl_chart: ^0.66.0
  
  # Date & Time
  date_picker_timeline: ^1.2.6
  
  # Forms & Validation
  formz: ^0.6.1
  
  # JSON & Serialization
  json_annotation: ^4.8.1
  
  # Loading & Progress Indicators
  loading_animation_widget: ^1.2.0+4
  
  # Firebase & Authentication (adicione se precisar de Firebase)
  # firebase_core: ^2.24.2
  # firebase_auth: ^4.15.3
  # google_sign_in: ^6.1.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  
  # Testing
  mockito: ^5.4.2
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true
  
  # Assets - SEÇÃO DESCOMENTADA E CONFIGURADA
  assets:
    - assets/images/
    - assets/icons/
    # Se você tiver outros tipos de assets, adicione aqui:
    # - assets/fonts/
    # - assets/data/
  
  # Fontes customizadas (descomente se precisar)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Italic.ttf
  #         style: italic