name: broke_club
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  uuid: ^4.2.1
  intl: ^0.19.0
  http: ^1.2.2
  fl_chart: ^0.66.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0